version: '3.8'

services:
  app:
    container_name: botFarm-app
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn botFarm:main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./botFarm:/src/app
    ports:
      - ${APP_HOST_PORT}:8001
    restart: always
    env_file:
      - .env
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data: